# Site settings
title: Tea In Coffee
email: jianpro_foxmail_com
description: "blog tech stuff"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: lovocas
github_username:  moujian

# Build settings
markdown: redcarpet
permalink: pretty

kramdown:
  input: GFM
analytics :
  provider : google
  google : 
        tracking_id : 'UA-123-12'
